;;; auto-generated from file #P"/Users/asf/Documents/hack/autobench/cl-bench/generate.lisp"
(IN-PACKAGE :CL-USER)
(LOAD #P"defpackage.lisp")
(COMPILE-FILE #P"files/arrays.olisp")
(COMPILE-FILE #P"files/bignum.olisp")
(COMPILE-FILE #P"files/boehm-gc.olisp")
(COMPILE-FILE #P"files/clos.olisp")
(COMPILE-FILE #P"files/crc40.olisp")
(COMPILE-FILE #P"files/deflate.olisp")
(COMPILE-FILE #P"files/gabriel.olisp")
(COMPILE-FILE #P"files/hash.olisp")
(COMPILE-FILE #P"files/math.olisp")
(COMPILE-FILE #P"files/ratios.olisp")
(COMPILE-FILE #P"files/richards.olisp")
(COMPILE-FILE #P"files/misc.olisp")
