;;; auto-generated from file #P"/Users/asf/Documents/hack/autobench/cl-bench/generate.lisp"
(IN-PACKAGE :CL-USER)
(LOAD #P"defpackage.lisp")
(LOAD (COMPILE-FILE-PATHNAME #P"files/arrays.olisp"))
(LOAD (COMPILE-FILE-PATHNAME #P"files/bignum.olisp"))
(LOAD (COMPILE-FILE-PATHNAME #P"files/boehm-gc.olisp"))
(LOAD (COMPILE-FILE-PATHNAME #P"files/clos.olisp"))
(LOAD (COMPILE-FILE-PATHNAME #P"files/crc40.olisp"))
(LOAD (COMPILE-FILE-PATHNAME #P"files/deflate.olisp"))
(LOAD (COMPILE-FILE-PATHNAME #P"files/gabriel.olisp"))
(LOAD (COMPILE-FILE-PATHNAME #P"files/hash.olisp"))
(LOAD (COMPILE-FILE-PATHNAME #P"files/math.olisp"))
(LOAD (COMPILE-FILE-PATHNAME #P"files/ratios.olisp"))
(LOAD (COMPILE-FILE-PATHNAME #P"files/richards.olisp"))
(LOAD (COMPILE-FILE-PATHNAME #P"files/misc.olisp"))
(COMPILE-FILE #P"support.lisp")
(LOAD (COMPILE-FILE-PATHNAME #P"support.lisp"))
(IN-PACKAGE :CL-BENCH)
(defun run-benchmarks ()
 (with-open-file (f (benchmark-report-file)
                    :direction :output
                    :if-does-not-exist :create
                    :if-exists :supersede)
   (let ((*benchmark-output* f)
         (*print-length* nil)
         (*load-verbose* nil)
         (*compile-verbose* nil)
         (*compile-print* nil)
	 (benchmarks-to-run
	  (with-open-file (f #p"benchmarks-to-run"
			   :direction :input
			   :if-does-not-exist :create)
	   (let ((*read-eval* nil))
	     (read f nil nil)))))
     (bench-report-header)

#-(OR ARMEDBEAR)
(when (run-benchmark-p 'COMPILER benchmarks-to-run)
  (format t "=== running #<benchmark COMPILER for 5 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.MISC:RUN-COMPILER "COMPILER" 5))

#-(OR ARMEDBEAR)
(when (run-benchmark-p 'LOAD-FASL benchmarks-to-run)
  (format t "=== running #<benchmark LOAD-FASL for 136 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.MISC:RUN-FASLOAD "LOAD-FASL" 136))

#-(OR LISPWORKS-PERSONAL-EDITION)
(when (run-benchmark-p 'SUM-PERMUTATIONS benchmarks-to-run)
  (format t "=== running #<benchmark SUM-PERMUTATIONS for 5 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.MISC:RUN-PERMUTATIONS "SUM-PERMUTATIONS" 5))

#-(OR LISPWORKS-PERSONAL-EDITION)
(when (run-benchmark-p 'WALK-LIST/SEQ benchmarks-to-run)
  (format t "=== running #<benchmark WALK-LIST/SEQ for 156 runs>~%")
  (force-output)
  (bench-gc)
  (funcall 'CL-BENCH.MISC::SETUP-WALK-LIST/SEQ)
  (BENCH-REPORT 'CL-BENCH.MISC:WALK-LIST/SEQ "WALK-LIST/SEQ" 156))

#-(OR LISPWORKS-PERSONAL-EDITION POPLOG)
(when (run-benchmark-p 'WALK-LIST/MESS benchmarks-to-run)
  (format t "=== running #<benchmark WALK-LIST/MESS for 17 runs>~%")
  (force-output)
  (bench-gc)
  (funcall 'CL-BENCH.MISC::SETUP-WALK-LIST/MESS)
  (BENCH-REPORT 'CL-BENCH.MISC:WALK-LIST/MESS "WALK-LIST/MESS" 17))
(when (run-benchmark-p 'BOYER benchmarks-to-run)
  (format t "=== running #<benchmark BOYER for 10 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.GABRIEL:BOYER "BOYER" 10))
(when (run-benchmark-p 'BROWSE benchmarks-to-run)
  (format t "=== running #<benchmark BROWSE for 63 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.GABRIEL:BROWSE "BROWSE" 63))
(when (run-benchmark-p 'DDERIV benchmarks-to-run)
  (format t "=== running #<benchmark DDERIV for 333 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.GABRIEL:DDERIV-RUN "DDERIV" 333))
(when (run-benchmark-p 'DERIV benchmarks-to-run)
  (format t "=== running #<benchmark DERIV for 351 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.GABRIEL:DERIV-RUN "DERIV" 351))
(when (run-benchmark-p 'DESTRUCTIVE benchmarks-to-run)
  (format t "=== running #<benchmark DESTRUCTIVE for 987 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.GABRIEL:RUN-DESTRUCTIVE "DESTRUCTIVE" 987))
(when (run-benchmark-p 'DIV2-TEST-1 benchmarks-to-run)
  (format t "=== running #<benchmark DIV2-TEST-1 for 785 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.GABRIEL:RUN-DIV2-TEST1 "DIV2-TEST-1" 785))
(when (run-benchmark-p 'DIV2-TEST-2 benchmarks-to-run)
  (format t "=== running #<benchmark DIV2-TEST-2 for 646 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.GABRIEL:RUN-DIV2-TEST2 "DIV2-TEST-2" 646))
(when (run-benchmark-p 'FFT benchmarks-to-run)
  (format t "=== running #<benchmark FFT for 2044 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.GABRIEL:RUN-FFT "FFT" 2044))
(when (run-benchmark-p 'FRPOLY/FIXNUM benchmarks-to-run)
  (format t "=== running #<benchmark FRPOLY/FIXNUM for 795 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.GABRIEL:RUN-FRPOLY/FIXNUM "FRPOLY/FIXNUM" 795))
(when (run-benchmark-p 'FRPOLY/BIGNUM benchmarks-to-run)
  (format t "=== running #<benchmark FRPOLY/BIGNUM for 335 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.GABRIEL:RUN-FRPOLY/BIGNUM "FRPOLY/BIGNUM" 335))
(when (run-benchmark-p 'FRPOLY/FLOAT benchmarks-to-run)
  (format t "=== running #<benchmark FRPOLY/FLOAT for 640 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.GABRIEL:RUN-FRPOLY/FLOAT "FRPOLY/FLOAT" 640))
(when (run-benchmark-p 'PUZZLE benchmarks-to-run)
  (format t "=== running #<benchmark PUZZLE for 23793 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.GABRIEL:RUN-PUZZLE "PUZZLE" 23793))
(when (run-benchmark-p 'TAK benchmarks-to-run)
  (format t "=== running #<benchmark TAK for 6159 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.GABRIEL:RUN-TAK "TAK" 6159))
(when (run-benchmark-p 'CTAK benchmarks-to-run)
  (format t "=== running #<benchmark CTAK for 11838 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.GABRIEL:RUN-CTAK "CTAK" 11838))
(when (run-benchmark-p 'TRTAK benchmarks-to-run)
  (format t "=== running #<benchmark TRTAK for 6173 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.GABRIEL:RUN-TRTAK "TRTAK" 6173))
(when (run-benchmark-p 'TAKL benchmarks-to-run)
  (format t "=== running #<benchmark TAKL for 1357 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.GABRIEL:RUN-TAKL "TAKL" 1357))
(when (run-benchmark-p 'STAK benchmarks-to-run)
  (format t "=== running #<benchmark STAK for 1576 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.GABRIEL:RUN-STAK "STAK" 1576))
(when (run-benchmark-p 'FPRINT/UGLY benchmarks-to-run)
  (format t "=== running #<benchmark FPRINT/UGLY for 315 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.GABRIEL:FPRINT/UGLY "FPRINT/UGLY" 315))
(when (run-benchmark-p 'FPRINT/PRETTY benchmarks-to-run)
  (format t "=== running #<benchmark FPRINT/PRETTY for 61 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.GABRIEL:FPRINT/PRETTY "FPRINT/PRETTY" 61))
(when (run-benchmark-p 'TRAVERSE benchmarks-to-run)
  (format t "=== running #<benchmark TRAVERSE for 20 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.GABRIEL:RUN-TRAVERSE "TRAVERSE" 20))
(when (run-benchmark-p 'TRIANGLE benchmarks-to-run)
  (format t "=== running #<benchmark TRIANGLE for 27 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.GABRIEL:RUN-TRIANGLE "TRIANGLE" 27))
(when (run-benchmark-p 'RICHARDS benchmarks-to-run)
  (format t "=== running #<benchmark RICHARDS for 34 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.RICHARDS:RICHARDS "RICHARDS" 34))
(when (run-benchmark-p 'FACTORIAL benchmarks-to-run)
  (format t "=== running #<benchmark FACTORIAL for 15853 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.MATH:RUN-FACTORIAL "FACTORIAL" 15853))
(when (run-benchmark-p 'FIB benchmarks-to-run)
  (format t "=== running #<benchmark FIB for 590 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.MATH:RUN-FIB "FIB" 590))
(when (run-benchmark-p 'FIB-RATIO benchmarks-to-run)
  (format t "=== running #<benchmark FIB-RATIO for 38806 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.MATH:RUN-FIB-RATIO "FIB-RATIO" 38806))
(when (run-benchmark-p 'ACKERMANN benchmarks-to-run)
  (format t "=== running #<benchmark ACKERMANN for 1 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.MATH:RUN-ACKERMANN "ACKERMANN" 1))
(when (run-benchmark-p 'MANDELBROT/COMPLEX benchmarks-to-run)
  (format t "=== running #<benchmark MANDELBROT/COMPLEX for 539 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.MATH:RUN-MANDELBROT/COMPLEX "MANDELBROT/COMPLEX" 539))
(when (run-benchmark-p 'MANDELBROT/DFLOAT benchmarks-to-run)
  (format t "=== running #<benchmark MANDELBROT/DFLOAT for 993 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.MATH:RUN-MANDELBROT/DFLOAT "MANDELBROT/DFLOAT" 993))
(when (run-benchmark-p 'MRG32K3A benchmarks-to-run)
  (format t "=== running #<benchmark MRG32K3A for 1000 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.MATH:RUN-MRG32K3A "MRG32K3A" 1000))
(when (run-benchmark-p 'CRC40 benchmarks-to-run)
  (format t "=== running #<benchmark CRC40 for 10 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.CRC:RUN-CRC40 "CRC40" 10))
(when (run-benchmark-p 'BIGNUM/ELEM-100-1000 benchmarks-to-run)
  (format t "=== running #<benchmark BIGNUM/ELEM-100-1000 for 36 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.BIGNUM:RUN-ELEM-100-1000 "BIGNUM/ELEM-100-1000" 36))
(when (run-benchmark-p 'BIGNUM/ELEM-1000-100 benchmarks-to-run)
  (format t "=== running #<benchmark BIGNUM/ELEM-1000-100 for 32 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.BIGNUM:RUN-ELEM-1000-100 "BIGNUM/ELEM-1000-100" 32))
(when (run-benchmark-p 'BIGNUM/ELEM-10000-1 benchmarks-to-run)
  (format t "=== running #<benchmark BIGNUM/ELEM-10000-1 for 56 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.BIGNUM:RUN-ELEM-10000-1 "BIGNUM/ELEM-10000-1" 56))
(when (run-benchmark-p 'BIGNUM/PARI-100-10 benchmarks-to-run)
  (format t "=== running #<benchmark BIGNUM/PARI-100-10 for 223 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.BIGNUM:RUN-PARI-100-10 "BIGNUM/PARI-100-10" 223))
(when (run-benchmark-p 'BIGNUM/PARI-200-5 benchmarks-to-run)
  (format t "=== running #<benchmark BIGNUM/PARI-200-5 for 84 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.BIGNUM:RUN-PARI-200-5 "BIGNUM/PARI-200-5" 84))
(when (run-benchmark-p 'PI-DECIMAL/SMALL benchmarks-to-run)
  (format t "=== running #<benchmark PI-DECIMAL/SMALL for 556 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.BIGNUM:RUN-PI-DECIMAL/SMALL "PI-DECIMAL/SMALL" 556))
(when (run-benchmark-p 'PI-DECIMAL/BIG benchmarks-to-run)
  (format t "=== running #<benchmark PI-DECIMAL/BIG for 90 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.BIGNUM:RUN-PI-DECIMAL/BIG "PI-DECIMAL/BIG" 90))
(when (run-benchmark-p 'PI-ATAN benchmarks-to-run)
  (format t "=== running #<benchmark PI-ATAN for 1046 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.BIGNUM:RUN-PI-ATAN "PI-ATAN" 1046))
(when (run-benchmark-p 'PI-RATIOS benchmarks-to-run)
  (format t "=== running #<benchmark PI-RATIOS for 6 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.RATIOS:RUN-PI-RATIOS "PI-RATIOS" 6))
(when (run-benchmark-p 'SLURP-LINES benchmarks-to-run)
  (format t "=== running #<benchmark SLURP-LINES for 45 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.HASH:RUN-SLURP-LINES "SLURP-LINES" 45))
(when (run-benchmark-p 'HASH-STRINGS benchmarks-to-run)
  (format t "=== running #<benchmark HASH-STRINGS for 18 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.HASH:HASH-STRINGS "HASH-STRINGS" 18))
(when (run-benchmark-p 'HASH-INTEGERS benchmarks-to-run)
  (format t "=== running #<benchmark HASH-INTEGERS for 34 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.HASH:HASH-INTEGERS "HASH-INTEGERS" 34))

#-(OR LISPWORKS-PERSONAL-EDITION)
(when (run-benchmark-p 'BOEHM-GC benchmarks-to-run)
  (format t "=== running #<benchmark BOEHM-GC for 2 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.BOEHM-GC:GC-BENCHMARK "BOEHM-GC" 2))
(when (run-benchmark-p 'DEFLATE-FILE benchmarks-to-run)
  (format t "=== running #<benchmark DEFLATE-FILE for 815 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.DEFLATE:RUN-DEFLATE-FILE "DEFLATE-FILE" 815))

#-(OR LISPWORKS-PERSONAL-EDITION)
(when (run-benchmark-p '1D-ARRAYS benchmarks-to-run)
  (format t "=== running #<benchmark 1D-ARRAYS for 360 runs>~%")
  (force-output)
  (bench-gc)
  (funcall 'CL-BENCH.ARRAYS:BENCH-1D-ARRAYS-SETUP)
  (BENCH-REPORT 'CL-BENCH.ARRAYS:BENCH-1D-ARRAYS "1D-ARRAYS" 360))

#-(OR LISPWORKS-PERSONAL-EDITION)
(when (run-benchmark-p '2D-ARRAYS benchmarks-to-run)
  (format t "=== running #<benchmark 2D-ARRAYS for 60 runs>~%")
  (force-output)
  (bench-gc)
  (funcall 'CL-BENCH.ARRAYS:BENCH-2D-ARRAYS-SETUP)
  (BENCH-REPORT 'CL-BENCH.ARRAYS:BENCH-2D-ARRAYS "2D-ARRAYS" 60))

#-(OR LISPWORKS-PERSONAL-EDITION)
(when (run-benchmark-p '3D-ARRAYS benchmarks-to-run)
  (format t "=== running #<benchmark 3D-ARRAYS for 20 runs>~%")
  (force-output)
  (bench-gc)
  (funcall 'CL-BENCH.ARRAYS:BENCH-3D-ARRAYS-SETUP)
  (BENCH-REPORT 'CL-BENCH.ARRAYS:BENCH-3D-ARRAYS "3D-ARRAYS" 20))
(when (run-benchmark-p 'BITVECTORS benchmarks-to-run)
  (format t "=== running #<benchmark BITVECTORS for 7700 runs>~%")
  (force-output)
  (bench-gc)
  (funcall 'CL-BENCH.ARRAYS:BENCH-BITVECTORS-SETUP)
  (BENCH-REPORT 'CL-BENCH.ARRAYS:BENCH-BITVECTORS "BITVECTORS" 7700))

#-(OR LISPWORKS-PERSONAL-EDITION)
(when (run-benchmark-p 'BENCH-STRINGS benchmarks-to-run)
  (format t "=== running #<benchmark BENCH-STRINGS for 300 runs>~%")
  (force-output)
  (bench-gc)
  (funcall 'CL-BENCH.ARRAYS:BENCH-STRINGS-SETUP)
  (BENCH-REPORT 'CL-BENCH.ARRAYS:BENCH-STRINGS "BENCH-STRINGS" 300))

#-(OR LISPWORKS-PERSONAL-EDITION)
(when (run-benchmark-p 'FILL-STRINGS/ADJUST benchmarks-to-run)
  (format t "=== running #<benchmark fill-strings/adjustable for 400 runs>~%")
  (force-output)
  (bench-gc)
  (funcall 'CL-BENCH.ARRAYS:BENCH-STRINGS/ADJUSTABLE)
  (BENCH-REPORT 'CL-BENCH.ARRAYS:BENCH-STRINGS/ADJUSTABLE "fill-strings/adjustable" 400))

#-(OR CLISP ALLEGRO LISPWORKS-PERSONAL-EDITION POPLOG)
(when (run-benchmark-p 'STRING-CONCAT benchmarks-to-run)
  (format t "=== running #<benchmark STRING-CONCAT for 100 runs>~%")
  (force-output)
  (bench-gc)
  (funcall 'CL-BENCH.ARRAYS:BENCH-STRING-CONCAT-SETUP)
  (BENCH-REPORT 'CL-BENCH.ARRAYS:BENCH-STRING-CONCAT "STRING-CONCAT" 100))

#-(OR LISPWORKS-PERSONAL-EDITION)
(when (run-benchmark-p 'SEARCH-SEQUENCE benchmarks-to-run)
  (format t "=== running #<benchmark SEARCH-SEQUENCE for 10 runs>~%")
  (force-output)
  (bench-gc)
  (funcall 'CL-BENCH.ARRAYS:BENCH-SEARCH-SEQUENCE-SETUP)
  (BENCH-REPORT 'CL-BENCH.ARRAYS:BENCH-SEARCH-SEQUENCE "SEARCH-SEQUENCE" 10))
(when (run-benchmark-p 'CLOS-DEFCLASS benchmarks-to-run)
  (format t "=== running #<benchmark CLOS/defclass for 1 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.CLOS:RUN-DEFCLASS "CLOS/defclass" 1))
(when (run-benchmark-p 'CLOS-DEFMETHOD benchmarks-to-run)
  (format t "=== running #<benchmark CLOS/defmethod for 1 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.CLOS:RUN-DEFMETHOD "CLOS/defmethod" 1))
(when (run-benchmark-p 'CLOS-INSTANTIATE benchmarks-to-run)
  (format t "=== running #<benchmark CLOS/instantiate for 2 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.CLOS:MAKE-INSTANCES "CLOS/instantiate" 2))
(when (run-benchmark-p 'CLOS-INSTANTIATE benchmarks-to-run)
  (format t "=== running #<benchmark CLOS/simple-instantiate for 1000 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.CLOS:MAKE-INSTANCES/SIMPLE "CLOS/simple-instantiate" 1000))
(when (run-benchmark-p 'METHODCALLS benchmarks-to-run)
  (format t "=== running #<benchmark CLOS/methodcalls for 5 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.CLOS:METHODCALLS/SIMPLE "CLOS/methodcalls" 5))
(when (run-benchmark-p 'METHODCALLS+AFTER benchmarks-to-run)
  (format t "=== running #<benchmark CLOS/method+after for 2 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.CLOS:METHODCALLS/SIMPLE+AFTER "CLOS/method+after" 2))

#-(OR CLISP POPLOG)
(when (run-benchmark-p 'METHODCALLS/COMPLEX benchmarks-to-run)
  (format t "=== running #<benchmark CLOS/complex-methods for 20 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.CLOS:METHODCALLS/COMPLEX "CLOS/complex-methods" 20))
(when (run-benchmark-p 'EQL-SPECIALIZED-FIB benchmarks-to-run)
  (format t "=== running #<benchmark EQL-SPECIALIZED-FIB for 33 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.CLOS:RUN-EQL-FIB "EQL-SPECIALIZED-FIB" 33))
(when (run-benchmark-p 'MAKE-LIST-SEQUENTIAL/PUSH-NREVERSE benchmarks-to-run)
  (format t "=== running #<benchmark MAKE-LIST-SEQUENTIAL/PUSH-NREVERSE for 4 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.MISC:MAKE-LIST-SEQUENTIAL/PUSH-NREVERSE "MAKE-LIST-SEQUENTIAL/PUSH-NREVERSE" 4))
(when (run-benchmark-p 'MAKE-LIST-SEQUENTIAL/RPLACD benchmarks-to-run)
  (format t "=== running #<benchmark MAKE-LIST-SEQUENTIAL/RPLACD for 4 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT 'CL-BENCH.MISC:MAKE-LIST-SEQUENTIAL/RPLACD "MAKE-LIST-SEQUENTIAL/RPLACD" 4))
(when (run-benchmark-p 'CORE-FILE-SIZE benchmarks-to-run)
  (format t "=== running #<benchmark CORE-FILE-SIZE for 1 runs>~%")
  (force-output)
  (bench-gc)
  (BENCH-REPORT-UNTIMED 'CL-BENCH.MISC:CORE-FILE-SIZE "CORE-FILE-SIZE" 1))
(bench-report-footer))))
(run-benchmarks)
