#!/bin/sh -e

. `dirname $0`/../functions
. /home/sbcl-arch/.ssh-agent

DIR=$1

cd $DIR

MVER=`sbcl-version`
ARCHIVEDIR=$BASE/build-archive/$MVER

COMPILELOG="$BASE/log.compile/manual-`date +%Y-%m-%d`-$MVER"

## add links to build archive if they exist

[ -f $ARCHIVEDIR/sbcl.gz ] && gunzip -f $ARCHIVEDIR/sbcl.gz
[ -f $ARCHIVEDIR/sbcl.core.gz ] && gunzip -f $ARCHIVEDIR/sbcl.core.gz
[ -f src/runtime/sbcl ] || ln -s $ARCHIVEDIR/sbcl src/runtime/sbcl
[ -f output/sbcl.core ] || ln -s $ARCHIVEDIR/sbcl.core output/sbcl.core

cd $DIR/doc/manual
gmake clean >$COMPILELOG 2>&1 </dev/null || exit 1
gmake >>$COMPILELOG 2>&1 </dev/null || exit 1
rm -rf manual || true
cp -Rp sbcl manual
tar zcf ~/www/sbcl.boinkor.net/manual/sbcl-manual.tgz manual
cat ~/www/sbcl.boinkor.net/manual/sbcl-manual.tgz | ssh antifuchs@shell.sf.net cd /home/groups/s/sb/sbcl/htdocs ";" tar zxf -

# clean up dirs
cd $DIR
for i in src/runtime/sbcl output/sbcl.core ; do
	[ -L $i ] &&  rm $i
done

# arch-tag: "100855f9-ff31-11d8-8b1b-000c76244c24"
