#!/bin/sh -xe

## scaffolding for building clisp. Assumes PWD is the clisp base dir.

CONFFLAGS=--without-readline

export CC=${1:-gcc}

./configure $CONFFLAGS
cd src
sh ./makemake $CONFFLAGS > Makefile
make config.lisp
make all
